### ISSUE TITLE
Fatal Exception during hide menu animation,Fab like a tumblr

### ISSUE THREAD

**Issue by saeedek** [ogaclejapan/ArcLayout#27]
Hello,
I have created the demo like a tumblr using my icons and buttons.the menu items works and animation is ok.but if I click on the fab and then click the fab again while the menu is on,I get this error : 
`FATAL EXCEPTION: main
                                                 Process: com.dsd2016.iparked_android, PID: 5694
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'long com.android.internal.util.VirtualRefBasePtr.get()' on a null object reference
                                                     at android.view.RenderNodeAnimator.applyInterpolator(RenderNodeAnimator.java:171)
                                                     at android.view.RenderNodeAnimator.start(RenderNodeAnimator.java:185)
                                                     at android.animation.AnimatorSet.start(AnimatorSet.java:678)
                                                     at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:807)
                                                     at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
                                                     at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
                                                     at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
                                                     at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
                                                     at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
                                                     at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
                                                     at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:616)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
`

**Comment by daniele-athome** [comment]
I have something similar on another library using a circular reveal animation. It might be an Android bug, but I'm not sure. Did you try the tumblr demo app in this library on your device?

I post my stacktrace for reference, on Replicant 6.0 running on a Samsung Galaxy S3 i9300:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.android.internal.util.VirtualRefBasePtr.get()' on a null object reference
    at android.view.RenderNodeAnimator.applyInterpolator(RenderNodeAnimator.java:171)
    at android.view.RenderNodeAnimator.start(RenderNodeAnimator.java:185)
    at io.codetail.animation.SupportAnimatorLollipop.start(SupportAnimatorLollipop.java:35)
    at org.kontalk.ui.view.AttachmentRevealFrameLayout.hide(AttachmentRevealFrameLayout.java:131)
    at org.kontalk.ui.view.AttachmentRevealFrameLayout.hide(AttachmentRevealFrameLayout.java:120)
    at org.kontalk.ui.view.AttachmentRevealFrameLayout.toggle(AttachmentRevealFrameLayout.java:137)
    at org.kontalk.ui.AbstractComposeFragment.toggleAttachmentView(AbstractComposeFragment.java:931)
    at org.kontalk.ui.AbstractComposeFragment.onOptionsItemSelected(AbstractComposeFragment.java:775)
    at org.kontalk.ui.ComposeMessageFragment.onOptionsItemSelected(ComposeMessageFragment.java:122)
    at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2309)
    at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2973)
    at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:414)
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
    at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
    at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21158)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
