### ISSUE TITLE
Setting ProgressView visibility in xml throws exception

### ISSUE THREAD

**Issue by jush** [ogaclejapan/ArcLayout#4]
Add a ProgressView widget in an xml with visiblity gone:

``` xml
    <com.rey.material.widget.ProgressView
        android:id="@+id/progressBar1"
        android:layout_width="56dp"
        android:layout_height="56dp"
        android:layout_gravity="center"
        android:visibility="gone"
        app:pv_autostart="false"
        app:pv_circular="true"
        app:pv_progressMode="indeterminate"
        app:pv_progressStyle="@style/MultipleColorsCircularProgressStyle"/>
```

Throws the following exception when running the app and during inflation:

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.rey.material.drawable.LinearProgressDrawable.getProgressMode()' on a null object reference
            at com.rey.material.widget.ProgressView.getProgressMode(ProgressView.java:125)
            at com.rey.material.widget.ProgressView.onVisibilityChanged(ProgressView.java:98)
            at android.view.View.dispatchVisibilityChanged(View.java:8731)
            at android.view.View.setFlags(View.java:9774)
            at android.view.View.<init>(View.java:4159)
            at android.view.View.<init>(View.java:3645)
            at com.rey.material.widget.ProgressView.<init>(ProgressView.java:45)
            at com.rey.material.widget.ProgressView.<init>(ProgressView.java:35)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
```

**Comment by jush** [comment]
Wrong repository, sorry about that.
